# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B4omrBDL__aorSb7rsy3qMsT9KMl3bD2
"""

import os
import re
import pandas as pd
import requests
import streamlit as st
from dotenv import load_dotenv

from langchain_groq import ChatGroq
from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.tools import tool
from langchain_core.prompts import ChatPromptTemplate

load_dotenv()

# --- 1. MONDAY.COM DATA FETCHING & CLEANING ---
def fetch_monday_board(board_id):
    url = "https://api.monday.com/v2"
    headers = {
        "Authorization": os.getenv("MONDAY_API_KEY"),
        "Content-Type": "application/json"
    }

    query = f"""
    query {{
      boards (ids: {board_id}) {{
        items_page {{
          items {{
            name
            column_values {{
              text
              column {{ title }}
            }}
          }}
        }}
      }}
    }}
    """

    response = requests.post(url, json={'query': query}, headers=headers)

    if response.status_code != 200:
        return None

    try:
        data = response.json()['data']['boards'][0]['items_page']['items']
    except Exception:
        return None

    rows = []
    for item in data:
        row = {"Item Name": item['name']}
        for col in item['column_values']:
            row[col['column']['title']] = col['text']
        rows.append(row)

    df = pd.DataFrame(rows)

    def clean_text(text):
        if not text:
            return "0"
        return re.sub(r'[\\"]', '', str(text)).strip()

    for col in df.columns:
        df[col] = df[col].apply(clean_text)

    return df


# --- 2. TOOLS FOR THE AGENT ---
@tool
def query_deals_pipeline(query_description: str):
    """Fetches and analyzes live sales pipeline data (Deals) from Monday.com."""
    df = fetch_monday_board(os.getenv("DEALS_BOARD_ID"))
    if df is None:
        return "Error fetching Deals board data."
    return df.to_string()


@tool
def query_work_orders(query_description: str):
    """Fetches and analyzes project execution data (Work Orders) from Monday.com."""
    df = fetch_monday_board(os.getenv("WORK_BOARD_ID"))
    if df is None:
        return "Error fetching Work Orders board data."
    return df.to_string()


tools = [query_deals_pipeline, query_work_orders]


# --- 3. AGENT SETUP ---
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

prompt = ChatPromptTemplate.from_messages([
    ("system", """You are a Business Intelligence Agent for a CEO.
You have access to 'Deals' and 'Work Orders' boards.

IMPORTANT:
1. Data is messy. 'Naruto', 'Sasuke', and 'Alias_X' are real project names.
2. If values are missing, state it as a 'Data Quality Caveat'.
3. Always check BOTH boards if the user asks about revenue vs pipeline.
4. Provide executive summaries with bullet points.
"""),
    ("placeholder", "{chat_history}"),
    ("human", "{input}"),
    ("placeholder", "{agent_scratchpad}"),
])

agent = create_tool_calling_agent(llm, tools, prompt)

agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True
)


# --- 4. STREAMLIT UI ---
st.set_page_config(page_title="Monday BI Agent", layout="wide")
st.title("📊 Monday.com BI Agent")

if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

if user_prompt := st.chat_input("Ask about your pipeline or work orders..."):
    st.session_state.messages.append({"role": "user", "content": user_prompt})

    with st.chat_message("user"):
        st.markdown(user_prompt)

    with st.chat_message("assistant"):
        with st.status("🔍 Agent is analyzing boards...", expanded=True) as status:
            response = agent_executor.invoke({"input": user_prompt})
            status.update(label="✅ Analysis Complete!", state="complete")

        st.markdown(response["output"])
        st.session_state.messages.append(
            {"role": "assistant", "content": response["output"]}
        )

